-- Seed de ejercicios para FitPilot con soporte bilingüe (EN/ES)
-- Ejecutar con: docker exec -i fitpilot_postgres psql -U admin -d fitpilot_db < seed_exercises.sql

-- Limpiar datos existentes (opcional - comentar si quieres mantener datos)
-- DELETE FROM exercise_muscles;
-- DELETE FROM exercises;

-- =====================================================
-- PECHO (Chest)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Flat Barbell Bench Press', 'Press de Banca Plano con Barra', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Lie on flat bench, grip bar slightly wider than shoulder width, lower to chest and press up', 'Acostado en banco plano, agarra la barra ligeramente más ancho que los hombros, baja al pecho y empuja hacia arriba', 'barbell, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Incline Barbell Bench Press', 'Press de Banca Inclinado con Barra', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Same as flat bench press but on an incline bench targeting upper chest', 'Igual que press plano pero en banco inclinado para pecho superior', 'barbell, incline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Bench Press', 'Press de Banca con Mancuernas', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Bench press variation with dumbbells allowing greater range of motion', 'Variante de press con mancuernas permitiendo mayor rango de movimiento', 'dumbbells, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Incline Dumbbell Press', 'Press Inclinado con Mancuernas', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Dumbbell press on incline bench for upper chest development', 'Press con mancuernas en banco inclinado para desarrollo del pecho superior', 'dumbbells, incline bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Decline Bench Press', 'Press de Banca Declinado', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Bench press on decline bench targeting lower chest', 'Press en banco declinado para pecho inferior', 'barbell, decline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Fly', 'Aperturas con Mancuernas', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Chest fly movement with dumbbells on flat bench', 'Movimiento de apertura con mancuernas en banco plano', 'dumbbells, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Incline Dumbbell Fly', 'Aperturas Inclinadas con Mancuernas', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Chest fly on incline bench for upper chest', 'Apertura en banco inclinado para pecho superior', 'dumbbells, incline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Crossover', 'Cruce de Poleas', 'MONOARTICULAR', 'FLAT', 'Fly', 'Standing cable fly movement for chest', 'Movimiento de apertura de pie con poleas para pecho', 'cables', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Pec Deck Machine', 'Máquina Pec Deck', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Machine chest fly exercise', 'Ejercicio de apertura de pecho en máquina', 'pec deck machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Push-ups', 'Flexiones', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Classic bodyweight chest exercise', 'Ejercicio clásico de pecho con peso corporal', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Chest Press Machine', 'Máquina Press de Pecho', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Machine assisted chest press', 'Press de pecho asistido por máquina', 'chest press machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Pullover', 'Pullover con Mancuerna', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Lying dumbbell pullover for chest and lats', 'Pullover acostado con mancuerna para pecho y dorsales', 'dumbbell, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Low to High Cable Fly', 'Cruce de Poleas Bajo a Alto', 'MONOARTICULAR', 'FLAT', 'Fly', 'Cable fly from low to high targeting upper chest', 'Cruce de poleas desde abajo hacia arriba para pecho superior', 'cables', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'High to Low Cable Fly', 'Cruce de Poleas Alto a Bajo', 'MONOARTICULAR', 'FLAT', 'Fly', 'Cable fly from high to low targeting lower chest', 'Cruce de poleas desde arriba hacia abajo para pecho inferior', 'cables', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Close Grip Push-ups', 'Flexiones Agarre Cerrado', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Push-ups with hands close together for inner chest and triceps', 'Flexiones con manos juntas para pecho interno y tríceps', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Smith Machine Bench Press', 'Press de Banca en Máquina Smith', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Bench press on Smith machine for controlled movement', 'Press de banca en máquina Smith para movimiento controlado', 'smith machine, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Decline Dumbbell Press', 'Press Declinado con Mancuernas', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Dumbbell press on decline bench for lower chest', 'Press con mancuernas en banco declinado para pecho inferior', 'dumbbells, decline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Wide Grip Push-ups', 'Flexiones Agarre Ancho', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Push-ups with wide hand placement for outer chest', 'Flexiones con manos separadas para pecho externo', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Machine Fly', 'Máquina de Aperturas', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Machine fly exercise for chest isolation', 'Apertura en máquina para aislamiento de pecho', 'fly machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Svend Press', 'Press Svend', 'MONOARTICULAR', 'FLAT', 'Press', 'Plate squeeze press for inner chest', 'Press apretando discos para pecho interno', 'weight plate', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- ESPALDA (Back)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Pull-ups', 'Dominadas', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Classic bodyweight back exercise using overhand grip', 'Ejercicio clásico de espalda con peso corporal usando agarre prono', 'pull-up bar', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Chin-ups', 'Dominadas Supinas', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Pull-up variation with underhand grip targeting biceps more', 'Variante de dominada con agarre supino enfocando más los bíceps', 'pull-up bar', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Lat Pulldown', 'Jalón al Pecho', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Cable pulldown exercise for lats', 'Ejercicio de jalón en polea para dorsales', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Wide Grip Lat Pulldown', 'Jalón al Pecho Agarre Ancho', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Lat pulldown with wide grip for outer lats', 'Jalón con agarre ancho para dorsales externos', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Close Grip Lat Pulldown', 'Jalón al Pecho Agarre Cerrado', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Lat pulldown with close grip', 'Jalón con agarre cerrado', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Barbell Row', 'Remo con Barra', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'Bent over barbell row for back thickness', 'Remo inclinado con barra para grosor de espalda', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Row', 'Remo con Mancuerna', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'Single arm dumbbell row for back', 'Remo con mancuerna a una mano para espalda', 'dumbbell, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Seated Cable Row', 'Remo Sentado en Polea', 'MULTIARTICULAR', 'FLAT', 'Row', 'Seated cable row for middle back', 'Remo sentado en polea para espalda media', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'T-Bar Row', 'Remo en T', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'T-bar row for back thickness', 'Remo en T para grosor de espalda', 'barbell, landmine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Deadlift', 'Peso Muerto', 'MULTIARTICULAR', 'ASCENDING', 'Deadlift', 'Conventional deadlift for full posterior chain', 'Peso muerto convencional para toda la cadena posterior', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Romanian Deadlift', 'Peso Muerto Rumano', 'MULTIARTICULAR', 'ASCENDING', 'Deadlift', 'Stiff-legged deadlift variation for hamstrings', 'Variante de peso muerto para isquiotibiales', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Face Pull', 'Tirón Facial', 'MONOARTICULAR', 'FLAT', 'Pull', 'Cable face pull for rear delts and rotator cuff', 'Tirón facial en polea para deltoides posterior y manguito rotador', 'cables, rope attachment', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Pendlay Row', 'Remo Pendlay', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'Explosive barbell row from floor with strict form', 'Remo explosivo con barra desde el suelo con forma estricta', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Meadows Row', 'Remo Meadows', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'Single arm landmine row for back thickness', 'Remo a una mano con landmine para grosor de espalda', 'barbell, landmine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Single Arm Lat Pulldown', 'Jalón Unilateral', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Single arm cable pulldown for lat isolation', 'Jalón a un brazo en polea para aislamiento de dorsales', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Straight Arm Pulldown', 'Jalón con Brazos Rectos', 'MONOARTICULAR', 'DESCENDING', 'Pull', 'Standing straight arm pulldown for lats', 'Jalón de pie con brazos rectos para dorsales', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Rack Pull', 'Peso Muerto desde Rack', 'MULTIARTICULAR', 'ASCENDING', 'Deadlift', 'Partial deadlift from knee height for upper back', 'Peso muerto parcial desde rodillas para espalda alta', 'barbell, rack', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Inverted Row', 'Remo Invertido', 'MULTIARTICULAR', 'DESCENDING', 'Row', 'Bodyweight row using bar or rings', 'Remo con peso corporal usando barra o anillas', 'bar, rings', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Good Morning', 'Buenos Días', 'MULTIARTICULAR', 'ASCENDING', 'Deadlift', 'Hip hinge exercise for lower back and hamstrings', 'Ejercicio de bisagra de cadera para espalda baja e isquiotibiales', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Neutral Grip Lat Pulldown', 'Jalón Agarre Neutro', 'MULTIARTICULAR', 'DESCENDING', 'Pull', 'Lat pulldown with neutral grip handle', 'Jalón con agarre neutro', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Row (Close Grip)', 'Remo en Polea Agarre Cerrado', 'MULTIARTICULAR', 'FLAT', 'Row', 'Seated cable row with close grip for middle back', 'Remo sentado con agarre cerrado para espalda media', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Seal Row', 'Remo Seal', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'Lying chest supported barbell row', 'Remo acostado con soporte de pecho', 'barbell, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Chest Supported Row', 'Remo con Apoyo de Pecho', 'MULTIARTICULAR', 'ASCENDING', 'Row', 'Incline bench supported dumbbell row', 'Remo con mancuernas apoyado en banco inclinado', 'dumbbells, incline bench', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- HOMBROS (Shoulders)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Overhead Press', 'Press Militar', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Standing barbell shoulder press', 'Press de hombros de pie con barra', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Shoulder Press', 'Press de Hombros con Mancuernas', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Seated or standing dumbbell shoulder press', 'Press de hombros sentado o de pie con mancuernas', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Arnold Press', 'Press Arnold', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Rotating dumbbell shoulder press variation', 'Variante de press con rotación de mancuernas', 'dumbbells', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Lateral Raise (Dumbbell)', 'Elevación Lateral con Mancuernas', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Dumbbell lateral raise for side delts', 'Elevación lateral con mancuernas para deltoides lateral', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Lateral Raise (Cable)', 'Elevación Lateral en Polea', 'MONOARTICULAR', 'FLAT', 'Raise', 'Cable lateral raise for constant tension', 'Elevación lateral en polea para tensión constante', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Lateral Raise (Machine)', 'Elevación Lateral en Máquina', 'MONOARTICULAR', 'FLAT', 'Raise', 'Machine lateral raise for side delts', 'Elevación lateral en máquina para deltoides lateral', 'lateral raise machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Front Raise', 'Elevación Frontal', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Front dumbbell raise for anterior delts', 'Elevación frontal con mancuernas para deltoides anterior', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Rear Delt Fly', 'Aperturas para Deltoides Posterior', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Bent over fly for rear delts', 'Apertura inclinado para deltoides posterior', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Reverse Pec Deck', 'Pec Deck Inverso', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Reverse pec deck for rear delts', 'Pec deck inverso para deltoides posterior', 'pec deck machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Shrugs (Dumbbell)', 'Encogimientos con Mancuernas', 'MONOARTICULAR', 'FLAT', 'Raise', 'Dumbbell shrugs for trapezius', 'Encogimientos con mancuernas para trapecios', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Shrugs (Barbell)', 'Encogimientos con Barra', 'MONOARTICULAR', 'FLAT', 'Raise', 'Barbell shrugs for trapezius', 'Encogimientos con barra para trapecios', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Upright Row', 'Remo al Mentón', 'MULTIARTICULAR', 'ASCENDING', 'Pull', 'Barbell or dumbbell upright row for shoulders', 'Remo al mentón con barra o mancuernas para hombros', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'High Pull', 'Tirón Alto', 'MULTIARTICULAR', 'ASCENDING', 'Pull', 'Explosive pull for shoulders and traps', 'Tirón explosivo para hombros y trapecios', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cuban Press', 'Press Cubano', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Rotational shoulder press for rotator cuff', 'Press de hombros con rotación para manguito rotador', 'dumbbells', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Lu Raise', 'Elevación Lu', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Front to lateral raise combination', 'Combinación de elevación frontal a lateral', 'dumbbells', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Seated Bent Over Rear Delt Fly', 'Aperturas Posterior Sentado', 'MONOARTICULAR', 'BELL_SHAPED', 'Fly', 'Seated bent over fly for rear delts', 'Apertura inclinado sentado para deltoides posterior', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Shoulder Press Machine', 'Press de Hombros en Máquina', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Machine assisted shoulder press', 'Press de hombros asistido por máquina', 'shoulder press machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Lateral Raise', 'Elevación Lateral con Cable', 'MONOARTICULAR', 'FLAT', 'Raise', 'Single arm cable lateral raise', 'Elevación lateral a un brazo con cable', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Behind Neck Press', 'Press Tras Nuca', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Overhead press behind the neck (requires good mobility)', 'Press sobre la cabeza por detrás (requiere buena movilidad)', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leaning Lateral Raise', 'Elevación Lateral Inclinado', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Single arm lateral raise while leaning for full ROM', 'Elevación lateral a un brazo inclinado para ROM completo', 'dumbbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Face Pull', 'Tirón Facial con Cable', 'MONOARTICULAR', 'FLAT', 'Pull', 'Cable face pull variation with external rotation', 'Variación de tirón facial con rotación externa', 'cables, rope attachment', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- PIERNAS (Legs)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Back Squat', 'Sentadilla Trasera', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Barbell back squat for overall leg development', 'Sentadilla trasera con barra para desarrollo general de piernas', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Front Squat', 'Sentadilla Frontal', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Barbell front squat emphasizing quads', 'Sentadilla frontal con barra enfatizando cuádriceps', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Goblet Squat', 'Sentadilla Goblet', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Dumbbell or kettlebell squat held at chest', 'Sentadilla con mancuerna o kettlebell sostenida al pecho', 'dumbbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leg Press', 'Prensa de Pierna', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Machine leg press for quads and glutes', 'Prensa de pierna para cuádriceps y glúteos', 'leg press machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hack Squat', 'Sentadilla Hack', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Machine hack squat for quads', 'Sentadilla hack en máquina para cuádriceps', 'hack squat machine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Bulgarian Split Squat', 'Sentadilla Búlgara', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Single leg squat with rear foot elevated', 'Sentadilla a una pierna con pie trasero elevado', 'dumbbells, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leg Extension', 'Extensión de Pierna', 'MONOARTICULAR', 'ASCENDING', 'Extension', 'Machine leg extension for quads isolation', 'Extensión de pierna en máquina para aislamiento de cuádriceps', 'leg extension machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Lying Leg Curl', 'Curl de Pierna Acostado', 'MONOARTICULAR', 'ASCENDING', 'Curl', 'Lying leg curl for hamstrings', 'Curl de pierna acostado para isquiotibiales', 'leg curl machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Seated Leg Curl', 'Curl de Pierna Sentado', 'MONOARTICULAR', 'ASCENDING', 'Curl', 'Seated leg curl for hamstrings', 'Curl de pierna sentado para isquiotibiales', 'leg curl machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Walking Lunge', 'Zancada Caminando', 'MULTIARTICULAR', 'ASCENDING', 'Lunge', 'Walking lunges for legs and glutes', 'Zancadas caminando para piernas y glúteos', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Step-ups', 'Subidas a Banco', 'MULTIARTICULAR', 'ASCENDING', 'Lunge', 'Step-ups on box or bench', 'Subidas a caja o banco', 'dumbbells, box', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Smith Machine Squat', 'Sentadilla en Máquina Smith', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Squat using Smith machine for stability', 'Sentadilla en máquina Smith para estabilidad', 'smith machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Sissy Squat', 'Sentadilla Sissy', 'MONOARTICULAR', 'ASCENDING', 'Squat', 'Bodyweight quad isolation exercise', 'Ejercicio de aislamiento de cuádriceps con peso corporal', 'bodyweight, support', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Pendulum Squat', 'Sentadilla Péndulo', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Machine squat with pendulum mechanism', 'Sentadilla en máquina con mecanismo de péndulo', 'pendulum squat machine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Belt Squat', 'Sentadilla con Cinturón', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Squat using belt machine for reduced spinal load', 'Sentadilla con máquina de cinturón para reducir carga espinal', 'belt squat machine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Barbell Lunges', 'Zancadas con Barra', 'MULTIARTICULAR', 'ASCENDING', 'Lunge', 'Forward lunges with barbell on back', 'Zancadas hacia adelante con barra en espalda', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Single Leg Press', 'Prensa de Pierna Unilateral', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Single leg press for unilateral leg development', 'Prensa a una pierna para desarrollo unilateral', 'leg press machine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Single Leg Romanian Deadlift', 'Peso Muerto Rumano Unilateral', 'MULTIARTICULAR', 'ASCENDING', 'Deadlift', 'Single leg RDL for hamstrings and balance', 'Peso muerto rumano a una pierna para isquiotibiales y equilibrio', 'dumbbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Nordic Curl', 'Curl Nórdico', 'MONOARTICULAR', 'DESCENDING', 'Curl', 'Bodyweight hamstring curl exercise', 'Ejercicio de curl de isquiotibiales con peso corporal', 'bodyweight, anchor', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Reverse Lunge', 'Zancada Reversa', 'MULTIARTICULAR', 'ASCENDING', 'Lunge', 'Stepping backward lunge variation', 'Variante de zancada hacia atrás', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leg Press (High Foot)', 'Prensa de Pierna Pies Altos', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Leg press with high foot placement for glutes/hams', 'Prensa con pies altos para glúteos e isquiotibiales', 'leg press machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leg Press (Low Foot)', 'Prensa de Pierna Pies Bajos', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Leg press with low foot placement for quads', 'Prensa con pies bajos para cuádriceps', 'leg press machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Pistol Squat', 'Sentadilla Pistola', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Single leg bodyweight squat', 'Sentadilla a una pierna con peso corporal', 'bodyweight', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Sumo Squat', 'Sentadilla Sumo', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Wide stance squat targeting adductors', 'Sentadilla con postura amplia para aductores', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Standing Leg Curl', 'Curl de Pierna de Pie', 'MONOARTICULAR', 'ASCENDING', 'Curl', 'Single leg standing hamstring curl', 'Curl de isquiotibiales de pie a una pierna', 'leg curl machine', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- GLÚTEOS (Glutes)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Hip Thrust (Barbell)', 'Empuje de Cadera con Barra', 'MULTIARTICULAR', 'ASCENDING', 'Thrust', 'Barbell hip thrust for glutes', 'Empuje de cadera con barra para glúteos', 'barbell, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hip Thrust (Dumbbell)', 'Empuje de Cadera con Mancuerna', 'MULTIARTICULAR', 'ASCENDING', 'Thrust', 'Dumbbell hip thrust variation', 'Variante de empuje de cadera con mancuerna', 'dumbbell, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Glute Bridge', 'Puente de Glúteos', 'MULTIARTICULAR', 'ASCENDING', 'Thrust', 'Floor glute bridge exercise', 'Puente de glúteos en el suelo', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Pull Through', 'Pull Through en Polea', 'MULTIARTICULAR', 'FLAT', 'Thrust', 'Cable pull through for glutes and hamstrings', 'Pull through en polea para glúteos e isquiotibiales', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hip Abduction Machine', 'Máquina de Abducción de Cadera', 'MONOARTICULAR', 'ASCENDING', 'Abduction', 'Machine hip abduction for glute medius', 'Abducción de cadera en máquina para glúteo medio', 'hip abduction machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hip Adduction Machine', 'Máquina de Aducción de Cadera', 'MONOARTICULAR', 'ASCENDING', 'Adduction', 'Machine hip adduction for inner thighs', 'Aducción de cadera en máquina para muslos internos', 'hip adduction machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Glute Kickback Machine', 'Patada de Glúteo en Máquina', 'MONOARTICULAR', 'ASCENDING', 'Extension', 'Machine kickback for glute isolation', 'Patada en máquina para aislamiento de glúteos', 'glute kickback machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Frog Pumps', 'Bombeo de Rana', 'MONOARTICULAR', 'ASCENDING', 'Thrust', 'Glute bridge variation with feet together', 'Variante de puente de glúteos con pies juntos', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Banded Hip Thrust', 'Empuje de Cadera con Banda', 'MULTIARTICULAR', 'ASCENDING', 'Thrust', 'Hip thrust with resistance band around knees', 'Empuje de cadera con banda de resistencia en rodillas', 'resistance band, bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Sumo Deadlift', 'Peso Muerto Sumo', 'MULTIARTICULAR', 'ASCENDING', 'Deadlift', 'Wide stance deadlift for glutes and adductors', 'Peso muerto con postura amplia para glúteos y aductores', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Kickback', 'Patada de Glúteo en Polea', 'MONOARTICULAR', 'FLAT', 'Extension', 'Cable kickback for glute isolation', 'Patada en polea para aislamiento de glúteos', 'cables, ankle strap', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Single Leg Hip Thrust', 'Empuje de Cadera Unilateral', 'MULTIARTICULAR', 'ASCENDING', 'Thrust', 'Single leg hip thrust for unilateral glute work', 'Empuje de cadera a una pierna para trabajo unilateral', 'bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Reverse Hyperextension', 'Hiperextensión Inversa', 'MULTIARTICULAR', 'ASCENDING', 'Extension', 'Reverse hyper for glutes and lower back', 'Hiperextensión inversa para glúteos y espalda baja', 'reverse hyper machine', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Donkey Kick', 'Patada de Burro', 'MONOARTICULAR', 'ASCENDING', 'Extension', 'Quadruped kickback for glutes', 'Patada en cuadrupedia para glúteos', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Fire Hydrant', 'Hidrante', 'MONOARTICULAR', 'ASCENDING', 'Abduction', 'Quadruped hip abduction for glute medius', 'Abducción de cadera en cuadrupedia para glúteo medio', 'bodyweight', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- PANTORRILLAS (Calves)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Standing Calf Raise', 'Elevación de Talones de Pie', 'MONOARTICULAR', 'ASCENDING', 'Raise', 'Standing calf raise machine', 'Elevación de talones de pie en máquina', 'calf raise machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Seated Calf Raise', 'Elevación de Talones Sentado', 'MONOARTICULAR', 'ASCENDING', 'Raise', 'Seated calf raise for soleus', 'Elevación de talones sentado para sóleo', 'calf raise machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leg Press Calf Raise', 'Elevación de Talones en Prensa', 'MONOARTICULAR', 'ASCENDING', 'Raise', 'Calf raises on leg press machine', 'Elevación de talones en máquina de prensa', 'leg press machine', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- BÍCEPS (Biceps)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Barbell Curl', 'Curl con Barra', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Standing barbell curl for biceps', 'Curl de pie con barra para bíceps', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'EZ Bar Curl', 'Curl con Barra EZ', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Curl with EZ bar for reduced wrist strain', 'Curl con barra EZ para reducir tensión en muñecas', 'ez bar', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Curl', 'Curl con Mancuernas', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Standing dumbbell curl', 'Curl de pie con mancuernas', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hammer Curl', 'Curl Martillo', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Neutral grip curl for brachialis', 'Curl con agarre neutro para braquial', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Preacher Curl', 'Curl Predicador', 'MONOARTICULAR', 'DESCENDING', 'Curl', 'Preacher bench curl for biceps peak', 'Curl en banco predicador para pico del bíceps', 'ez bar, preacher bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Incline Dumbbell Curl', 'Curl Inclinado con Mancuernas', 'MONOARTICULAR', 'ASCENDING', 'Curl', 'Incline bench curl for long head stretch', 'Curl en banco inclinado para estiramiento de cabeza larga', 'dumbbells, incline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Curl', 'Curl en Polea', 'MONOARTICULAR', 'FLAT', 'Curl', 'Cable curl for constant tension', 'Curl en polea para tensión constante', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Concentration Curl', 'Curl Concentrado', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Seated concentration curl for bicep peak', 'Curl concentrado sentado para pico del bíceps', 'dumbbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Spider Curl', 'Curl Araña', 'MONOARTICULAR', 'DESCENDING', 'Curl', 'Incline bench curl with arms hanging', 'Curl en banco inclinado con brazos colgando', 'dumbbells, incline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Reverse Curl', 'Curl Reverso', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Overhand grip curl for brachioradialis', 'Curl con agarre prono para braquiorradial', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'High Cable Curl', 'Curl de Cable Alto', 'MONOARTICULAR', 'FLAT', 'Curl', 'Overhead cable curl for bicep peak', 'Curl de cable sobre la cabeza para pico del bíceps', 'cables', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cross Body Hammer Curl', 'Curl Martillo Cruzado', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Hammer curl across the body for brachialis', 'Curl martillo cruzando el cuerpo para braquial', 'dumbbells', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Drag Curl', 'Curl Arrastre', 'MONOARTICULAR', 'ASCENDING', 'Curl', 'Barbell curl dragging the bar up the body', 'Curl con barra arrastrando la barra por el cuerpo', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Zottman Curl', 'Curl Zottman', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Curl with rotation for biceps and forearms', 'Curl con rotación para bíceps y antebrazos', 'dumbbells', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Machine Bicep Curl', 'Curl de Bíceps en Máquina', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Machine assisted bicep curl', 'Curl de bíceps asistido por máquina', 'bicep curl machine', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- TRÍCEPS (Triceps)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Close Grip Bench Press', 'Press de Banca Agarre Cerrado', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Bench press with close grip for triceps', 'Press de banca con agarre cerrado para tríceps', 'barbell, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Tricep Pushdown (Rope)', 'Extensión de Tríceps con Cuerda', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Cable pushdown with rope attachment', 'Extensión en polea con cuerda', 'cables, rope attachment', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Tricep Pushdown (V-Bar)', 'Extensión de Tríceps con V-Bar', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Cable pushdown with V-bar', 'Extensión en polea con V-bar', 'cables, v-bar', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Skull Crusher', 'Rompecráneos', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Lying tricep extension with EZ bar', 'Extensión de tríceps acostado con barra EZ', 'ez bar, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Overhead Tricep Extension', 'Extensión de Tríceps sobre Cabeza', 'MONOARTICULAR', 'ASCENDING', 'Extension', 'Overhead dumbbell tricep extension', 'Extensión de tríceps sobre la cabeza con mancuerna', 'dumbbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dips', 'Fondos en Paralelas', 'MULTIARTICULAR', 'ASCENDING', 'Dip', 'Parallel bar dips for triceps and chest', 'Fondos en paralelas para tríceps y pecho', 'parallel bars', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Bench Dips', 'Fondos en Banco', 'MULTIARTICULAR', 'ASCENDING', 'Dip', 'Dips using a bench', 'Fondos usando un banco', 'bench', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Tricep Kickback', 'Patada de Tríceps', 'MONOARTICULAR', 'ASCENDING', 'Extension', 'Bent over dumbbell kickback for triceps', 'Patada de tríceps inclinado con mancuerna', 'dumbbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Overhead Extension', 'Extensión Sobre Cabeza en Polea', 'MONOARTICULAR', 'ASCENDING', 'Extension', 'Overhead cable tricep extension', 'Extensión de tríceps sobre la cabeza en polea', 'cables, rope attachment', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Diamond Push-ups', 'Flexiones Diamante', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Push-ups with hands in diamond position', 'Flexiones con manos en posición de diamante', 'bodyweight', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'JM Press', 'Press JM', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Hybrid bench press and skull crusher for triceps', 'Híbrido de press de banca y rompecráneos para tríceps', 'barbell, bench', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Tate Press', 'Press Tate', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Dumbbell tricep extension with elbows out', 'Extensión de tríceps con mancuernas con codos hacia afuera', 'dumbbells, bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Single Arm Tricep Pushdown', 'Extensión de Tríceps Unilateral', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Single arm cable pushdown', 'Extensión en polea a un brazo', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Tricep Machine', 'Máquina de Tríceps', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Machine assisted tricep extension', 'Extensión de tríceps asistida por máquina', 'tricep machine', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'French Press', 'Press Francés', 'MONOARTICULAR', 'DESCENDING', 'Extension', 'Standing or seated overhead barbell extension', 'Extensión sobre la cabeza de pie o sentado con barra', 'ez bar', 'intermediate', 'strength', NOW(), NOW());

-- =====================================================
-- CORE / ABDOMINALES
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Plank', 'Plancha', 'MONOARTICULAR', 'FLAT', 'Static', 'Isometric plank hold for core stability', 'Plancha isométrica para estabilidad del core', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Crunches', 'Abdominales', 'MONOARTICULAR', 'BELL_SHAPED', 'Crunch', 'Basic crunch exercise for abs', 'Ejercicio básico de abdominal', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hanging Leg Raise', 'Elevación de Piernas Colgado', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Hanging leg raise for lower abs', 'Elevación de piernas colgado para abdominales inferiores', 'pull-up bar', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Cable Crunch', 'Crunch en Polea', 'MONOARTICULAR', 'DESCENDING', 'Crunch', 'Kneeling cable crunch for abs', 'Crunch de rodillas en polea para abdominales', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Russian Twist', 'Giro Ruso', 'MONOARTICULAR', 'FLAT', 'Rotation', 'Rotational core exercise', 'Ejercicio de rotación para core', 'weight plate', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Ab Wheel Rollout', 'Rueda Abdominal', 'MULTIARTICULAR', 'DESCENDING', 'Crunch', 'Ab wheel exercise for full core', 'Ejercicio de rueda abdominal para todo el core', 'ab wheel', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dead Bug', 'Dead Bug', 'MONOARTICULAR', 'FLAT', 'Static', 'Core stability exercise', 'Ejercicio de estabilidad del core', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Pallof Press', 'Press Pallof', 'MONOARTICULAR', 'FLAT', 'Press', 'Anti-rotation core exercise', 'Ejercicio anti-rotación para core', 'cables', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Side Plank', 'Plancha Lateral', 'MONOARTICULAR', 'FLAT', 'Static', 'Lateral plank for obliques', 'Plancha lateral para oblicuos', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Bicycle Crunch', 'Crunch Bicicleta', 'MONOARTICULAR', 'BELL_SHAPED', 'Crunch', 'Rotational crunch targeting obliques', 'Crunch rotacional para oblicuos', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'V-Up', 'V-Up', 'MONOARTICULAR', 'DESCENDING', 'Crunch', 'Full body crunch forming V shape', 'Crunch de cuerpo completo formando V', 'bodyweight', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dragon Flag', 'Bandera del Dragón', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Advanced core exercise keeping body straight', 'Ejercicio avanzado de core manteniendo el cuerpo recto', 'bench', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Woodchop (Cable)', 'Leñador en Polea', 'MULTIARTICULAR', 'FLAT', 'Rotation', 'Rotational cable movement for core', 'Movimiento rotacional en polea para core', 'cables', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Reverse Crunch', 'Crunch Inverso', 'MONOARTICULAR', 'DESCENDING', 'Crunch', 'Crunch lifting hips for lower abs', 'Crunch levantando caderas para abdominales inferiores', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Toe Touch', 'Toque de Dedos', 'MONOARTICULAR', 'BELL_SHAPED', 'Crunch', 'Lying toe touch crunch', 'Crunch tocando los dedos de los pies', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Flutter Kicks', 'Patadas Aleteo', 'MONOARTICULAR', 'FLAT', 'Raise', 'Alternating leg raises for lower abs', 'Elevaciones alternas de piernas para abdominales inferiores', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Leg Raise', 'Elevación de Piernas', 'MONOARTICULAR', 'DESCENDING', 'Raise', 'Lying leg raise for lower abs', 'Elevación de piernas acostado para abdominales inferiores', 'bodyweight', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Copenhagen Plank', 'Plancha Copenhague', 'MONOARTICULAR', 'FLAT', 'Static', 'Side plank variation with leg elevated', 'Variante de plancha lateral con pierna elevada', 'bench', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Decline Sit-ups', 'Abdominales Declinados', 'MONOARTICULAR', 'BELL_SHAPED', 'Crunch', 'Sit-ups on decline bench', 'Abdominales en banco declinado', 'decline bench', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Weighted Plank', 'Plancha con Peso', 'MONOARTICULAR', 'FLAT', 'Static', 'Plank with added weight on back', 'Plancha con peso adicional en la espalda', 'weight plate', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hollow Body Hold', 'Posición Hueca', 'MONOARTICULAR', 'FLAT', 'Static', 'Gymnastic core hold position', 'Posición de core gimnástica', 'bodyweight', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Superman', 'Superman', 'MONOARTICULAR', 'FLAT', 'Extension', 'Lying back extension for lower back', 'Extensión acostado para espalda baja', 'bodyweight', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- CARDIO
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, cardio_subclass, intensity_zone, target_heart_rate_min, target_heart_rate_max, calories_per_minute, created_at, updated_at) VALUES
(gen_random_uuid(), 'Treadmill Running', 'Correr en Cinta', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Running on treadmill', 'Correr en cinta de correr', 'treadmill', 'beginner', 'cardio', 'miss', 3, 130, 150, 10.0, NOW(), NOW()),
(gen_random_uuid(), 'Stationary Bike', 'Bicicleta Estática', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Cycling on stationary bike', 'Ciclismo en bicicleta estática', 'stationary bike', 'beginner', 'cardio', 'liss', 2, 100, 130, 6.0, NOW(), NOW()),
(gen_random_uuid(), 'Rowing Machine', 'Máquina de Remo', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Rowing ergometer exercise', 'Ejercicio en ergómetro de remo', 'rowing machine', 'beginner', 'cardio', 'miss', 3, 130, 150, 9.0, NOW(), NOW()),
(gen_random_uuid(), 'Elliptical', 'Elíptica', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Elliptical machine workout', 'Entrenamiento en máquina elíptica', 'elliptical machine', 'beginner', 'cardio', 'liss', 2, 100, 130, 6.0, NOW(), NOW()),
(gen_random_uuid(), 'Stair Climber', 'Escaladora', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Stair climbing machine', 'Máquina de subir escaleras', 'stair climber machine', 'beginner', 'cardio', 'liss', 2, 100, 130, 7.0, NOW(), NOW()),
(gen_random_uuid(), 'Battle Ropes', 'Cuerdas de Batalla', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'High intensity battle ropes', 'Cuerdas de batalla de alta intensidad', 'battle ropes', 'intermediate', 'cardio', 'hiit', 4, 150, 180, 12.0, NOW(), NOW()),
(gen_random_uuid(), 'Burpees', 'Burpees', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Full body cardio exercise', 'Ejercicio cardiovascular de cuerpo completo', 'bodyweight', 'intermediate', 'cardio', 'hiit', 4, 150, 180, 12.0, NOW(), NOW()),
(gen_random_uuid(), 'Jumping Jacks', 'Saltos de Tijera', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Classic jumping jack exercise', 'Ejercicio clásico de saltos de tijera', 'bodyweight', 'beginner', 'cardio', 'hiit', 4, 150, 180, 10.0, NOW(), NOW()),
(gen_random_uuid(), 'Mountain Climbers', 'Escaladores', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Mountain climber cardio exercise', 'Ejercicio cardiovascular de escaladores', 'bodyweight', 'beginner', 'cardio', 'hiit', 4, 150, 180, 11.0, NOW(), NOW()),
(gen_random_uuid(), 'Jump Rope', 'Saltar la Cuerda', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Skipping rope cardio exercise', 'Ejercicio cardiovascular de saltar la cuerda', 'jump rope', 'beginner', 'cardio', 'miss', 3, 130, 160, 11.0, NOW(), NOW()),
(gen_random_uuid(), 'Assault Bike', 'Bicicleta Assault', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Air bike with arm movement', 'Bicicleta de aire con movimiento de brazos', 'assault bike', 'beginner', 'cardio', 'hiit', 4, 150, 180, 14.0, NOW(), NOW()),
(gen_random_uuid(), 'Sled Push', 'Empuje de Trineo', 'MULTIARTICULAR', 'ASCENDING', 'Cardio', 'Pushing weighted sled for conditioning', 'Empujar trineo con peso para acondicionamiento', 'sled', 'intermediate', 'cardio', 'hiit', 4, 150, 180, 12.0, NOW(), NOW()),
(gen_random_uuid(), 'Sled Pull', 'Tirón de Trineo', 'MULTIARTICULAR', 'ASCENDING', 'Cardio', 'Pulling weighted sled backwards', 'Tirar del trineo con peso hacia atrás', 'sled, rope', 'intermediate', 'cardio', 'hiit', 4, 150, 180, 11.0, NOW(), NOW()),
(gen_random_uuid(), 'High Knees', 'Rodillas Altas', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Running in place with high knees', 'Correr en el lugar con rodillas altas', 'bodyweight', 'beginner', 'cardio', 'hiit', 4, 150, 175, 10.0, NOW(), NOW()),
(gen_random_uuid(), 'Butt Kicks', 'Talones a Glúteos', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Running in place kicking heels to glutes', 'Correr en el lugar llevando talones a glúteos', 'bodyweight', 'beginner', 'cardio', 'hiit', 3, 130, 160, 9.0, NOW(), NOW()),
(gen_random_uuid(), 'Sprint Intervals', 'Intervalos de Sprint', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'High intensity sprint intervals', 'Intervalos de sprint de alta intensidad', 'treadmill, track', 'intermediate', 'cardio', 'hiit', 5, 170, 190, 15.0, NOW(), NOW()),
(gen_random_uuid(), 'Swimming', 'Natación', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Swimming laps for cardio', 'Nadar largos para cardio', 'pool', 'beginner', 'cardio', 'liss', 2, 110, 140, 8.0, NOW(), NOW()),
(gen_random_uuid(), 'Versa Climber', 'Versa Climber', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Vertical climbing machine', 'Máquina de escalada vertical', 'versa climber', 'intermediate', 'cardio', 'hiit', 4, 150, 180, 13.0, NOW(), NOW()),
(gen_random_uuid(), 'Ski Erg', 'Ski Erg', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Ski ergometer for upper body cardio', 'Ergómetro de ski para cardio de tren superior', 'ski erg', 'beginner', 'cardio', 'miss', 3, 130, 160, 9.0, NOW(), NOW()),
(gen_random_uuid(), 'Walk', 'Caminar', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Low intensity walking', 'Caminata de baja intensidad', 'treadmill, outdoor', 'beginner', 'cardio', 'liss', 1, 90, 110, 4.0, NOW(), NOW()),
(gen_random_uuid(), 'Incline Treadmill Walk', 'Caminata en Cinta Inclinada', 'MULTIARTICULAR', 'FLAT', 'Cardio', 'Walking on incline treadmill for low impact cardio', 'Caminata en cinta inclinada para cardio de bajo impacto', 'treadmill', 'beginner', 'cardio', 'liss', 2, 100, 130, 6.0, NOW(), NOW());

-- =====================================================
-- CALENTAMIENTO Y MOVILIDAD
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Arm Circles', 'Círculos de Brazos', 'MONOARTICULAR', 'FLAT', 'Warmup', 'Arm circles for shoulder warm-up', 'Círculos de brazos para calentar hombros', 'bodyweight', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Leg Swings', 'Balanceo de Piernas', 'MONOARTICULAR', 'FLAT', 'Warmup', 'Dynamic leg swings for hip mobility', 'Balanceo dinámico de piernas para movilidad de cadera', 'bodyweight', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Hip Circles', 'Círculos de Cadera', 'MONOARTICULAR', 'FLAT', 'Warmup', 'Hip circles for mobility', 'Círculos de cadera para movilidad', 'bodyweight', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Cat-Cow Stretch', 'Estiramiento Gato-Vaca', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Spinal mobility exercise', 'Ejercicio de movilidad espinal', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'World Greatest Stretch', 'El Mejor Estiramiento del Mundo', 'MULTIARTICULAR', 'FLAT', 'Mobility', 'Comprehensive mobility stretch', 'Estiramiento integral de movilidad', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Band Pull Apart', 'Separación de Banda', 'MONOARTICULAR', 'FLAT', 'Warmup', 'Band pull apart for shoulder warm-up', 'Separación de banda para calentar hombros', 'resistance band', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Inchworm', 'Gusano', 'MULTIARTICULAR', 'FLAT', 'Warmup', 'Dynamic warm-up exercise', 'Ejercicio dinámico de calentamiento', 'bodyweight', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Foam Rolling Quads', 'Rodillo en Cuádriceps', 'MONOARTICULAR', 'FLAT', 'Recovery', 'Foam rolling for quad recovery', 'Rodillo de espuma para recuperación de cuádriceps', 'foam roller', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Thoracic Spine Rotation', 'Rotación de Columna Torácica', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Thoracic mobility exercise', 'Ejercicio de movilidad torácica', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Hip 90/90 Stretch', 'Estiramiento de Cadera 90/90', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Hip mobility stretch in 90/90 position', 'Estiramiento de movilidad de cadera en posición 90/90', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Shoulder Dislocates', 'Dislocaciones de Hombro', 'MONOARTICULAR', 'FLAT', 'Warmup', 'Shoulder mobility with band or stick', 'Movilidad de hombro con banda o palo', 'resistance band', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Couch Stretch', 'Estiramiento de Sofá', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Hip flexor and quad stretch', 'Estiramiento de flexor de cadera y cuádriceps', 'bench, wall', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Pigeon Stretch', 'Estiramiento de Paloma', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Hip opener stretch', 'Estiramiento de apertura de cadera', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Foam Rolling Back', 'Rodillo en Espalda', 'MONOARTICULAR', 'FLAT', 'Recovery', 'Foam rolling for back muscles', 'Rodillo de espuma para músculos de la espalda', 'foam roller', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Foam Rolling IT Band', 'Rodillo en Banda IT', 'MONOARTICULAR', 'FLAT', 'Recovery', 'Foam rolling for IT band', 'Rodillo de espuma para banda iliotibial', 'foam roller', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Wall Angels', 'Ángeles en Pared', 'MONOARTICULAR', 'FLAT', 'Warmup', 'Wall slide for shoulder mobility', 'Deslizamiento en pared para movilidad de hombros', 'wall', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'Scorpion Stretch', 'Estiramiento del Escorpión', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Lying spinal rotation stretch', 'Estiramiento de rotación espinal acostado', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'Frog Stretch', 'Estiramiento de Rana', 'MONOARTICULAR', 'FLAT', 'Mobility', 'Groin and hip adductor stretch', 'Estiramiento de ingle y aductores', 'bodyweight', 'beginner', 'mobility', NOW(), NOW()),
(gen_random_uuid(), 'A-Skips', 'Skips-A', 'MULTIARTICULAR', 'FLAT', 'Warmup', 'Dynamic warm-up skip drill', 'Ejercicio dinámico de calentamiento con saltos', 'bodyweight', 'beginner', 'warmup', NOW(), NOW()),
(gen_random_uuid(), 'B-Skips', 'Skips-B', 'MULTIARTICULAR', 'FLAT', 'Warmup', 'Dynamic warm-up skip drill with leg extension', 'Ejercicio dinámico de calentamiento con extensión de pierna', 'bodyweight', 'beginner', 'warmup', NOW(), NOW());

-- =====================================================
-- EJERCICIOS OLÍMPICOS Y PLIOMÉTRICOS
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Power Clean', 'Cargada de Potencia', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Olympic weightlifting power clean', 'Cargada de potencia del levantamiento olímpico', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Box Jumps', 'Saltos a Caja', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Explosive box jump exercise', 'Ejercicio explosivo de salto a caja', 'plyo box', 'intermediate', 'plyometric', NOW(), NOW()),
(gen_random_uuid(), 'Kettlebell Swing', 'Swing con Kettlebell', 'MULTIARTICULAR', 'BELL_SHAPED', 'Swing', 'Hip hinge kettlebell swing', 'Swing de kettlebell con bisagra de cadera', 'kettlebell', 'intermediate', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Thrusters', 'Thrusters', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Squat to overhead press combination', 'Combinación de sentadilla con press sobre cabeza', 'barbell', 'intermediate', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Hang Clean', 'Cargada Colgante', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Clean starting from hang position', 'Cargada comenzando desde posición colgante', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Snatch', 'Arrancada', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Olympic snatch from floor to overhead', 'Arrancada olímpica desde el suelo hasta sobre la cabeza', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Hang Snatch', 'Arrancada Colgante', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Snatch starting from hang position', 'Arrancada comenzando desde posición colgante', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Clean and Jerk', 'Cargada y Envión', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Full olympic clean and jerk', 'Cargada y envión olímpico completo', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Push Press', 'Press con Impulso', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Overhead press with leg drive', 'Press sobre la cabeza con impulso de piernas', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Push Jerk', 'Envión con Impulso', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Overhead jerk with leg drive and dip', 'Envión sobre la cabeza con impulso y hundimiento', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Depth Jump', 'Salto de Profundidad', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Drop from box and immediately jump', 'Caer de caja y saltar inmediatamente', 'plyo box', 'advanced', 'plyometric', NOW(), NOW()),
(gen_random_uuid(), 'Broad Jump', 'Salto Largo', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Standing horizontal jump for distance', 'Salto horizontal de pie para distancia', 'bodyweight', 'intermediate', 'plyometric', NOW(), NOW()),
(gen_random_uuid(), 'Tuck Jump', 'Salto con Rodillas', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Vertical jump bringing knees to chest', 'Salto vertical llevando rodillas al pecho', 'bodyweight', 'intermediate', 'plyometric', NOW(), NOW()),
(gen_random_uuid(), 'Medicine Ball Slam', 'Slam de Balón Medicinal', 'MULTIARTICULAR', 'DESCENDING', 'Plyometric', 'Explosive overhead slam with medicine ball', 'Slam explosivo sobre la cabeza con balón medicinal', 'medicine ball', 'beginner', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Medicine Ball Throw', 'Lanzamiento de Balón Medicinal', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Explosive chest pass with medicine ball', 'Pase de pecho explosivo con balón medicinal', 'medicine ball', 'beginner', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Wall Ball', 'Wall Ball', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Squat and throw medicine ball to wall', 'Sentadilla y lanzar balón medicinal a la pared', 'medicine ball, wall', 'beginner', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Lateral Box Jump', 'Salto Lateral a Caja', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Side-to-side box jump', 'Salto a caja de lado a lado', 'plyo box', 'intermediate', 'plyometric', NOW(), NOW()),
(gen_random_uuid(), 'Single Leg Box Jump', 'Salto a Caja Unilateral', 'MULTIARTICULAR', 'ASCENDING', 'Plyometric', 'Single leg jump onto box', 'Salto a caja con una pierna', 'plyo box', 'advanced', 'plyometric', NOW(), NOW()),
(gen_random_uuid(), 'Farmers Walk', 'Caminata del Granjero', 'MULTIARTICULAR', 'FLAT', 'Carry', 'Walking while holding heavy weights', 'Caminar mientras se sostienen pesos pesados', 'dumbbells, kettlebells', 'beginner', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Turkish Get Up', 'Levantamiento Turco', 'MULTIARTICULAR', 'FLAT', 'Olympic', 'Complex full body movement from lying to standing', 'Movimiento complejo de cuerpo completo de acostado a de pie', 'kettlebell', 'advanced', 'conditioning', NOW(), NOW()),
(gen_random_uuid(), 'Clean Pull', 'Tirón de Cargada', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Pulling portion of the clean without catch', 'Parte de tirón de la cargada sin recepción', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Snatch Pull', 'Tirón de Arrancada', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Pulling portion of the snatch without catch', 'Parte de tirón de la arrancada sin recepción', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Front Rack Lunge', 'Zancada con Rack Frontal', 'MULTIARTICULAR', 'ASCENDING', 'Lunge', 'Lunge with barbell in front rack position', 'Zancada con barra en posición de rack frontal', 'barbell', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Overhead Squat', 'Sentadilla sobre Cabeza', 'MULTIARTICULAR', 'ASCENDING', 'Squat', 'Squat with barbell held overhead', 'Sentadilla con barra sostenida sobre la cabeza', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Split Jerk', 'Envión con Split', 'MULTIARTICULAR', 'ASCENDING', 'Press', 'Jerk with split stance landing', 'Envión con aterrizaje en posición de split', 'barbell', 'advanced', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Muscle Snatch', 'Arrancada Muscular', 'MULTIARTICULAR', 'ASCENDING', 'Olympic', 'Snatch without receiving in overhead squat', 'Arrancada sin recepción en sentadilla sobre cabeza', 'barbell', 'intermediate', 'strength', NOW(), NOW());

-- =====================================================
-- ANTEBRAZOS Y AGARRE (Forearms and Grip)
-- =====================================================
INSERT INTO exercises (id, name_en, name_es, type, resistance_profile, category, description_en, description_es, equipment_needed, difficulty_level, exercise_class, created_at, updated_at) VALUES
(gen_random_uuid(), 'Wrist Curl', 'Curl de Muñeca', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Seated wrist curl for forearm flexors', 'Curl de muñeca sentado para flexores del antebrazo', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Reverse Wrist Curl', 'Curl de Muñeca Inverso', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Reverse wrist curl for forearm extensors', 'Curl de muñeca inverso para extensores del antebrazo', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Plate Pinch', 'Pinzamiento de Disco', 'MONOARTICULAR', 'FLAT', 'Static', 'Pinching weight plates together for grip', 'Pellizcar discos de peso para agarre', 'weight plates', 'intermediate', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Dead Hang', 'Colgado Muerto', 'MONOARTICULAR', 'FLAT', 'Static', 'Hanging from bar for grip endurance', 'Colgarse de la barra para resistencia de agarre', 'pull-up bar', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Finger Curls', 'Curls de Dedos', 'MONOARTICULAR', 'BELL_SHAPED', 'Curl', 'Finger curls for grip strength', 'Curls de dedos para fuerza de agarre', 'barbell', 'beginner', 'strength', NOW(), NOW()),
(gen_random_uuid(), 'Gripper', 'Ejercicio de Pinza', 'MONOARTICULAR', 'ASCENDING', 'Static', 'Hand gripper for crushing grip', 'Pinza de mano para agarre de aplastamiento', 'hand gripper', 'beginner', 'strength', NOW(), NOW());

-- =====================================================
-- Eliminar duplicados exactos (Farmer Carry es duplicado de Farmers Walk)
-- =====================================================
-- Los ejercicios ya están sin duplicados en este seed limpio
