-- Training migration baseline for Supabase target:
-- - Creates missing training tables required by legacy training data.
-- - Adds foreign keys to public.users so users have a single source of truth.
-- - Adds supporting indexes.

-- 1) Create missing legacy tables in training schema.

CREATE TABLE IF NOT EXISTS training.client_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL,
    metric_type VARCHAR(64) NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS training.patient_context_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id INTEGER NOT NULL,
    version VARCHAR(64) NOT NULL,
    effective_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source VARCHAR(50),
    data JSONB NOT NULL,
    created_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2) Add missing foreign keys to public.users.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'client_interviews'
          AND c.conname = 'client_interviews_client_id_public_users_fkey'
    ) THEN
        ALTER TABLE training.client_interviews
            ADD CONSTRAINT client_interviews_client_id_public_users_fkey
            FOREIGN KEY (client_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'workout_logs'
          AND c.conname = 'workout_logs_client_id_public_users_fkey'
    ) THEN
        ALTER TABLE training.workout_logs
            ADD CONSTRAINT workout_logs_client_id_public_users_fkey
            FOREIGN KEY (client_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'macrocycles'
          AND c.conname = 'macrocycles_trainer_id_public_users_fkey'
    ) THEN
        ALTER TABLE training.macrocycles
            ADD CONSTRAINT macrocycles_trainer_id_public_users_fkey
            FOREIGN KEY (trainer_id) REFERENCES public.users(id) ON DELETE NO ACTION;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'macrocycles'
          AND c.conname = 'macrocycles_client_id_public_users_fkey'
    ) THEN
        ALTER TABLE training.macrocycles
            ADD CONSTRAINT macrocycles_client_id_public_users_fkey
            FOREIGN KEY (client_id) REFERENCES public.users(id) ON DELETE NO ACTION;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'client_metrics'
          AND c.conname = 'client_metrics_client_id_public_users_fkey'
    ) THEN
        ALTER TABLE training.client_metrics
            ADD CONSTRAINT client_metrics_client_id_public_users_fkey
            FOREIGN KEY (client_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'patient_context_snapshots'
          AND c.conname = 'patient_context_snapshots_client_id_public_users_fkey'
    ) THEN
        ALTER TABLE training.patient_context_snapshots
            ADD CONSTRAINT patient_context_snapshots_client_id_public_users_fkey
            FOREIGN KEY (client_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'training'
          AND t.relname = 'patient_context_snapshots'
          AND c.conname = 'patient_context_snapshots_created_by_public_users_fkey'
    ) THEN
        ALTER TABLE training.patient_context_snapshots
            ADD CONSTRAINT patient_context_snapshots_created_by_public_users_fkey
            FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- 3) Add indexes for FK columns and frequent access paths.

CREATE INDEX IF NOT EXISTS idx_training_client_interviews_client_id
    ON training.client_interviews (client_id);

CREATE INDEX IF NOT EXISTS idx_training_workout_logs_client_id
    ON training.workout_logs (client_id);

CREATE INDEX IF NOT EXISTS idx_training_macrocycles_trainer_id
    ON training.macrocycles (trainer_id);

CREATE INDEX IF NOT EXISTS idx_training_macrocycles_client_id
    ON training.macrocycles (client_id);

CREATE INDEX IF NOT EXISTS idx_training_client_metrics_client_id
    ON training.client_metrics (client_id);

CREATE INDEX IF NOT EXISTS idx_training_patient_context_client_effective
    ON training.patient_context_snapshots (client_id, effective_at DESC);

CREATE INDEX IF NOT EXISTS idx_training_patient_context_created_by
    ON training.patient_context_snapshots (created_by);

